# Use root/example as user/password credentials
version: '3.9'

services:
  app:
    build:
      context: ./laec
      dockerfile: Dockerfile
    volumes:
      -  ./laec:/app
    entrypoint: ["./wait.sh"]
    environment:
      SECRET_KEY: qgjkldfjsjdjdflgjdfljgdsfklgjdlk
      DATABASE_NAME: laec
      DATABASE_USER: laec
      DATABASE_PASS: laec
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      ELASTICSEARCH_HOST: es
      ELASTICSEARCH_PORT: 9200
      PROD_HOST: localhost
    links:
      - db
      - selenium-hub
    ports:
      - "127.0.0.1:9000:8000"
      - "127.0.0.1:9876:9876"


  db:
    image: mysql:5.7
    #volumes:
    #  -  ./data:/var/lib/mysql
    command: ['mysqld','--default-authentication-plugin=mysql_native_password','--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    #restart: always
    environment:
      MYSQL_USER: laec
      MYSQL_PASSWORD: laec
      MYSQL_DATABASE: laec
      MYSQL_ROOT_PASSWORD: laec

  es:
    image: elasticsearch:5.6.5-alpine
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  chrome:
    image: selenium/node-chrome:4.1.1-20220121
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.1.1-20220121
    container_name: selenium-hub
    ports:
      - "127.0.0.1:4442:4442"
      - "127.0.0.1:4443:4443"
      - "127.0.0.1:4444:4444"
